name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  github:
    runs-on: ubuntu-20.04
    steps:
    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ "{{ secrets.GITHUB_TOKEN }}" }}
      with:
        tag_name: ${{ "{{ github.ref }}" }}
        release_name: Release ${{ "{{ github.ref }}" }}
        draft: false
        prerelease: false
  container:
    runs-on: ubuntu-20.04
    steps:
    - name: Authenticate with ghcr
      run: echo '${{ "{{ secrets.GITHUB_TOKEN }}" }}' | docker login ghcr.io -u ${{ "{{ github.repository_owner }}" }} --password-stdin
    - uses: actions/checkout@v2
    - name: Build container
      run: docker build -t ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/tags/} -f docker/Dockerfile .
    - name: Publish container
      run: docker push ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/tags/}
